//
// CartPaymentMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The payment method request for a cart. If the token is provided no card data is required. */
public struct CartPaymentMethod: Codable, JSONEncodable, Hashable {

    /** Generated payment token. */
    public var token: String?
    /** Number on the credit or debit card. */
    public var cardNumber: String?
    /** CVC code on the credit or debit card. */
    public var cardCvc: Int?
    /** Expiration month of the credit or debit card. */
    public var cardExpMonth: Int?
    /** Expiration year of the credit or debit card. */
    public var cardExpYear: Int?
    /** Postal Code of the credit or debit card. */
    public var cardPostalCode: String?

    public init(token: String? = nil, cardNumber: String? = nil, cardCvc: Int? = nil, cardExpMonth: Int? = nil, cardExpYear: Int? = nil, cardPostalCode: String? = nil) {
        self.token = token
        self.cardNumber = cardNumber
        self.cardCvc = cardCvc
        self.cardExpMonth = cardExpMonth
        self.cardExpYear = cardExpYear
        self.cardPostalCode = cardPostalCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case cardNumber = "card_number"
        case cardCvc = "card_cvc"
        case cardExpMonth = "card_exp_month"
        case cardExpYear = "card_exp_year"
        case cardPostalCode = "card_postal_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(cardNumber, forKey: .cardNumber)
        try container.encodeIfPresent(cardCvc, forKey: .cardCvc)
        try container.encodeIfPresent(cardExpMonth, forKey: .cardExpMonth)
        try container.encodeIfPresent(cardExpYear, forKey: .cardExpYear)
        try container.encodeIfPresent(cardPostalCode, forKey: .cardPostalCode)
    }
}

