//
// Dimension.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Individual Product Dimensions */
public struct Dimension: Codable, JSONEncodable, Hashable {

    public enum Measure: String, Codable, CaseIterable {
        case height = "height"
        case weight = "weight"
        case width = "width"
        case depth = "depth"
    }
    public enum ModelType: String, Codable, CaseIterable {
        case product = "product"
        case shipping = "shipping"
    }
    public enum UnitOfMeasure: String, Codable, CaseIterable {
        case inches = "inches"
        case feet = "feet"
        case centimeters = "centimeters"
        case ounces = "ounces"
        case pounds = "pounds"
        case grams = "grams"
        case kilograms = "kilograms"
    }
    public var id: Int64?
    /** Sku ID */
    public var skuId: Int64
    /** What's being measured */
    public var measure: Measure
    /** Type of Measurement */
    public var type: ModelType
    /** Unit of Measure */
    public var unitOfMeasure: UnitOfMeasure?
    /** Value */
    public var value: Double?

    public init(id: Int64? = nil, skuId: Int64, measure: Measure, type: ModelType, unitOfMeasure: UnitOfMeasure? = nil, value: Double? = nil) {
        self.id = id
        self.skuId = skuId
        self.measure = measure
        self.type = type
        self.unitOfMeasure = unitOfMeasure
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case skuId = "sku_id"
        case measure
        case type
        case unitOfMeasure = "unit_of_measure"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(skuId, forKey: .skuId)
        try container.encode(measure, forKey: .measure)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(unitOfMeasure, forKey: .unitOfMeasure)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

